project:
  type: book
  output-dir: docs

book:
  title: "Lesboek Oekra誰ens voor Nederlandstaligen"
  author: "Duco Veen, gebaseerd op GPT-4 output"
  date: "`r Sys.Date()`"
  chapters:
  - index.qmd
  - part: inleiding-tot-de-oekra誰ense-taal.qmd
    chapters: 
     # - geschiedenis-en-achtergrond.qmd
      - het-alfabet-en-de-uitspraak.qmd
      - basis-uitdrukkingen-en-woordenschat.qmd
  - part: Basisgrammatica.qmd
    chapters:
      - zelfstandige-naamwoorden.qmd
      - bijvoeglijke-naamwoorden.qmd
      - werkwoorden.qmd
      - telwoorden.qmd
      - voorzetsels-en-bijwoorden.qmd
  - part: Dagelijkse communicatie.qmd
    chapters:
      - hogere-getallen.qmd
  #     - begroetingen-en-afscheid-nemen.qmd
  #     - zichzelf-voorstellen-en-anderen-leren-kennen.qmd
  #     - eten-en-drinken.qmd
  #     - winkelen-en-betalen.qmd
  #     - vervoer-en-reizen.qmd
  # - part: Oefeningen en opdrachten.qmd
  #   chapters:
  #    - luisteroefeningen.qmd
  #    - leesoefeningen.qmd
  #    - schrijfoefeningen.qmd
  #    - spreek-en-conversatieoefeningen.qmd

# onderstaande nog aanpassen
#   part: "Woordenlijst en nuttige zinnen"
# chapters:
#   - "05-1-basiswoordenschat.qmd"
# - "05-2-nuttige-zinnen-voor-dagelijkse-situaties.qmd"
#   part: "Culturele aspecten van Oekra誰ne"
# chapters:
#   - "06-1-tradities-en-feestdagen.qmd"
# - "06-2-oekra誰ense-keuken.qmd"
# - "06-3-muziek-kunst-en-literatuur.qmd"
  - part: Appendixes.qmd
    chapters:
    - references.qmd  
    #- gpt4history.qmd

    
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
