# Basis Oekraïense uitdrukkingen en woordenschat

In dit hoofdstuk zullen we enkele basis Oekraïense uitdrukkingen, woordenschat en zinnen introduceren die u zullen helpen om vertrouwd te raken met de taal en eenvoudige gesprekken te voeren. We beginnen met persoonlijke voornaamwoorden, gevolgd door begroetingen en afscheid nemen, en andere veelgebruikte uitdrukkingen.

Dit hoofdstuk zal de lezer voorzien van de basiswoordenschat en uitdrukkingen die nodig zijn om eenvoudige gesprekken te voeren en te navigeren in alledaagse situaties. Het legt ook een basis voor verdere studie van de Oekraïense grammatica en complexere taalconstructies.

## Persoonlijke voornaamwoorden

Het is natuurlijk altijd handig om door te hebben over wie iets gaat. Daarom eerst maar eens kijken naar persoonlijke voornaamwoorden, hoe verwijs ik naar mezelf of een ander?

| Oekraïens | Nederlands  |      | Oekraïens | Nederlands  |
| --------- | ----------- | ---- | --------- | ----------- |
| я         | ik          |      | ми        | wij         |
| ти        | jij         |      | ви        | jullie      |
| він       | hij         |      | вони      | zij (mannelijk)    |
| вона      | zij (vrouwelijk) |      |           |             |
| воно      | het         |      |           |             |

## Begroetingen en afscheid nemen

Nu we iets van de persoonlijke voornaamwoorden weten wil *я* ook wel beleefd iemand kunnen groeten. Hoe werkt dat dan? Hier zijn enkele veelgebruikte Oekraïense begroetingen en manieren om afscheid te nemen:

| Oekraïens        | Uitspraak         | Nederlands      |
| ---------------- | ----------------- | --------------- |
| Привіт           | Pryvit            | Hallo           |
| Добрий ранок     | Dobryi ranok      | Goedemorgen     |
| Добрий день      | Dobryi den        | Goedemiddag     |
| Добрий вечір     | Dobryi vechir     | Goede avond     |
| Добраніч         | Dobranich         | Goede nacht     |
| Бувайте          | Buvayte           | Tot ziens       |
| До побачення     | Do pobachennya    | Tot ziens       |


## Beleefdheidsuitdrukkingen en basiszinnen

Naast het groeten kan het handig zijn om nog wat meer basis beleefdheidsvormen te leren voor we verder gaan. Immers, ook als je de taal verder nog niet beheerst, staat niets je in de weg om vriendelijk te zijn! Hier zijn enkele beleefdheidsuitdrukkingen en basiszinnen die vaak worden gebruikt in het Oekraïens:

| Oekraïens        | Uitspraak         | Nederlands      |
| ---------------- | ----------------- | --------------- |
| Будь ласка       | Bud' laska        | Alstublieft     |
| Дякую            | Dyakuyu           | Dank u          |
| Вибачте          | Vybachte          | Sorry           |
| Немає проблем    | Nemaye problem    | Geen probleem   |
| Як справи?       | Yak spravy?       | Hoe gaat het?   |
| Добре            | Dobre             | Goed            |
| Згода            | Zghoda            | Akkoord         |

## Persoonlijke informatie

Om een heleboel verschillende reden kan het praktisch zijn om iets over jezelf te kunnen delen. In deze sectie zullen we enkele woorden en zinnen bespreken die worden gebruikt om persoonlijke informatie in het Oekraïens te bespreken:

| Oekraïens        | Uitspraak         | Nederlands       |
| ---------------- | ----------------- | ---------------- |
| Ім'я             | Im'ya             | Naam             |
| Прізвище         | Prizvishche       | Achternaam       |
| Вік              | Vik               | Leeftijd         |
| Адреса           | Adresa            | Adres            |
| Місто            | Misto             | Stad             |
| Країна           | Kraina            | Land             |
| Рідна мова       | Ridna mova        | Moedertaal       |
| Зайнятість       | Zaynyatist'       | Beroep           |

Enkele voorbeeldzinnen zijn:

- Як тебе звати? (Yak tebe zvaty?) - Wat is je naam?
- Скільки тобі років? (Skilky tobi rokiv?) - Hoe oud ben je?
- Звідки ти? (Zvidky ty?) - Waar kom je vandaan?
- Що ти робиш? (Shcho ty robysh?) - Wat doe je (voor werk)?


## Familie en relaties

Nu we wat persoonlijke informatie weten is het wellicht ook handig om te kunen verwijzen naar familie en relaties. We bespreken de basiswoorden die betrekking hebben op familie en relaties in het Oekraïens. Dit zal je helpen om met Oekraïense vrienden en kennissen over familieleden te praten en je eigen gezin en relaties te beschrijven.

### Familieleden

| Oekraïens | Uitspraak | Nederlands |
|-----------|-----------|------------|
| сім'я | sim'ya | familie |
| батько | bat'ko | vader |
| мати | mati | moeder |
| брат | brat | broer |
| сестра | sestra | zus |
| дідусь | didus' | opa |
| бабуся | babusya | oma |
| син | syn | zoon |
| дочка | dochka | dochter |
| дядько | dyad'ko | oom |
| тітка | titka | tante |
| племінник | pleminnyk | neef |
| племінниця | pleminnytsya | nicht |
| чоловік | cholovik | echtgenoot |
| дружина | druzhyna | echtgenote |

### Relaties

| Oekraïens | Uitspraak | Nederlands |
|-----------|-----------|------------|
| друг | druh | vriend |
| подруга | podruga | vriendin |
| коханець | kohanets' | vriendje (romantisch) |
| коханка | kohanka | vriendinnetje (romantisch) |
| колега | kolega | collega |
| сусід | susid | buur(man) |
| сусідка | susidka | buurvrouw |

### Voorbeeldzinnen

1. Це мій брат. (Tse miy brat.) - Dit is mijn broer.
2. Моя сестра живе в Києві. (Moya sestra zhyve v Kyievi.) - Mijn zus woont in Kiev.
3. Він мій чоловік. (Vin miy cholovik.) - Hij is mijn echtgenoot.

## Getallen en tellen

In deze sectie zullen we de getallen in het Oekraïens leren, evenals enkele basisbegrippen met betrekking tot tellen en getallen. Laten we gelijk met de deur in huis vallen en de getallen van 1 tot 20 leren.

| Getal | Oekraïens | Uitspraak   | 
| --------- | --------- | ----------- | 
| 1         | один        | odyn       | 
| 2         | два         | dva        | 
| 3         | три         | try        | 
| 4         | чотири      | chotyry    | 
| 5         | п'ять       | pyat       | 
| 6         | шість       | shist      | 
| 7         | сім         | sim        | 
| 8         | вісім       | visim      | 
| 9         | дев'ять     | devyat     | 
| 10        | десять      | desyat     | 
| 11        | одинадцять  | odynadtsyat| 
| 12        | дванадцять  | dvanadtsyat| 
| 13        | тринадцять  | trynadtsyat| 
| 14        | чотирнадцять| chotyrnadtsyat| 
| 15        | п'ятнадцять | pyatnadtsyat| 
| 16        | шістнадцять | shistnadtsyat|
| 17        | сімнадцять  | simnadtsyat| 
| 18        | вісімнадцять| visimnadtsyat|
| 19        | дев'ятнадцять| devyatnadtsyat| 
| 20        | двадцять    | dvadtsyat  | 


Om de getallen van 1 tot en met 99 in het Oekraïens te leren, willen we misschien niet alles alleen maar uit ons hoofd leren. Het is belangrijk om de basisgetallen en enkele regels te begrijpen over hoe deze getallen gecombineerd worden. We hebben al de getallen van 1 tot en met 20 geleerd en moeten ook nog even de tientallen van 20 tot en met 90 samen bekijken:

| Getal | Oekraïens | Uitspraak   | 
| --------- | ----------- | ----------- |
| 20        | двадцять    | dvadtsyat   |
| 30        | тридцять    | trydtsyat   |
| 40        | сорок       | sorok       |
| 50        | п'ятдесят   | pyatdesyat  |
| 60        | шістдесят   | shistdesyat |
| 70        | сімдесят    | simdesyat   |
| 80        | вісімдесят  | visimdesyat |
| 90        | дев'яносто  | devyanosto  |


Om nu de getallen van 21 tot en met 99 te vormen, volg je deze stappen:

1. Begin met het tiental. Bijvoorbeeld, voor 25 begin je met "двадцять" (dvadtsyat), wat 20 betekent.
2. Voeg vervolgens het woord "і" (i) toe, wat "en" betekent.
3. Ten slotte voeg je het enkelvoudige cijfer toe, zoals "п'ять" (pyat) voor 5.

Dus het getal 25 wordt in het Oekraïens "двадцять і п'ять" (dvadtsyat i pyat).

Hier zijn enkele voorbeelden van getallen tussen 21 en 99:

| Getal | Oekraïens                 | Uitspraak              | 
| ------------------------- | ---------------------- | ---------- |
| 23                        | двадцять і три         | dvadtsyat i try         |
| 37                        | тридцять і сім         | trydtsyat i sim         |
| 48                        | сорок і вісім          | sorok i visim           |
| 59                        | п'ятдесят і дев'ять    | pyatdesyat i devyat     |
| 65                        | шістдесят і п'ять      | shistdesyat i pyat      |
| 78                        | сімдесят і вісім       | simdesyat i visim       |
| 86                        | вісімдесят і шість     | visimdesyat i shist     |
| 94                        | дев'яносто і чотири    | devyanosto i chotyry    |

Volg deze stappen en je kunt nu alle getallen van 1 tot en met 99 in het Oekraïens leren.

Naast de getallen van 1 tot 20, zijn er enkele andere belangrijke termen die u moet weten met betrekking tot getallen en tellen:

| Oekraïens | Uitspraak   | Nederlands  |
| --------- | ----------- | ----------- |
| нуль      | nul         | nul         |
| сто        | sto         | honderd     |
| тисяча     | tysiacha    | duizend     |
| мільйон    | mil'yon     | miljoen     |
| мільярд    | mil'yard    | miljard     |

Maar hoe kom je nou tot een beheersing van alle getallen tot aan deze miljard? In dit hoofdstuk is de bedoeling dat de lezer voorzien voorzien wordt van de basiswoordenschat en uitdrukkingen die nodig zijn om eenvoudige gesprekken te voeren en te navigeren in alledaagse situaties. Met de getallen tot en met honderd kom je in allerdaagse situaties een heel eind. Daarom stoppen we hier voor nu even. Maar geen zorgen, wil je hogere getallen leren, kijk dan voor de uitleg in @sec-hogere-getallen.


## Dagen van de week, maanden en seizoenen

Het kan ook erg praktisch zijn om te weten naar welke tijd verwezen wordt. Daarom gaan we in deze sectie de dagen van de week, maanden en seizoenen in het Oekraïens leren.

### Dagen van de week

Hier is een tabel met de dagen van de week in het Oekraïens, samen met de uitspraak en de Nederlandse vertaling:

| Oekraïens     | Uitspraak     | Nederlands    |
| ------------- | ------------- | ------------- |
| понеділок     | ponedylok     | maandag       |
| вівторок      | vivtorok      | dinsdag       |
| середа        | sereda        | woensdag      |
| четвер        | chetver       | donderdag     |
| п'ятниця      | pyatnytsya    | vrijdag       |
| субота        | subota        | zaterdag      |
| неділя        | nedilya       | zondag        |

### Maanden

Hier is een tabel met de maanden van het jaar in het Oekraïens, samen met de uitspraak en de Nederlandse vertaling:

| Oekraïens      | Uitspraak      | Nederlands    |
| -------------- | -------------- | ------------- |
| січень         | sichen         | januari       |
| лютий          | lyutyi         | februari      |
| березень       | berezen        | maart         |
| квітень        | kviten         | april         |
| травень        | traven         | mei           |
| червень        | cherven        | juni          |
| липень         | lypen          | juli          |
| серпень        | serpen         | augustus      |
| вересень       | veresen        | september     |
| жовтень        | zhovten        | oktober       |
| листопад       | lystopad       | november      |
| грудень        | hruden         | december      |

### Seizoenen

Hier is een tabel met de vier seizoenen in het Oekraïens, samen met de uitspraak en de Nederlandse vertaling:

| Oekraïens    | Uitspraak    | Nederlands |
| ------------ | ------------ | ---------- |
| весна        | vesna        | lente      |
| літо         | lito         | zomer      |
| осінь        | osin         | herfst     |
| зима         | zyma         | winter     |


## Eten en drinken

Begin je al een beetje in te komen met het Oekraïens? Dan krijg je misschien wel dorst of trek. In deze sectie introduceren we een aantal van de meest voorkomende en cultureel relevante dranken en gerechten in Oekraïne. Oekraïense keuken is rijk aan smaken en tradities en kan variëren van regio tot regio.

### Dranken

1. **Компот (Kompot)** - uitspraak: _kompot_ - Een traditionele Oekraïense drank gemaakt van gekookt fruit, meestal bessen, en suiker. Het kan zowel warm als koud worden geserveerd.
2. **Узвар (Uzvar)** - uitspraak: _uzvar_ - Een drank gemaakt van gedroogde vruchten, zoals appels, peren en pruimen, gekookt in water. Het is een populair drankje tijdens de kerstperiode.
3. **Горілка (Horilka)** - uitspraak: _horilka_ - Oekraïense wodka, meestal gemaakt van tarwe of rogge. Het heeft een hoog alcoholgehalte en wordt vaak koud geserveerd tijdens feestelijke gelegenheden.
4. **Пиво (Pyvo)** - uitspraak: _pyvo_ - Bier is een populaire drank in Oekraïne, met veel lokale brouwerijen die verschillende stijlen en smaken produceren. Enkele bekende Oekraïense biermerken zijn Оболонь (Obolon), Чернігівське (Chernihivske) en Львівське (Lvivske).
5. **Вино (Vyno)** - uitspraak: _vyno_ - Hoewel Oekraïne niet zo bekend staat om zijn wijnen als andere Europese landen, zijn er toch enkele wijnregio's in het land, voornamelijk in het zuiden en westen. Populaire Oekraïense wijnen zijn gemaakt van druivensoorten zoals Ркацители (Rkatsiteli), Аліготе (Aligote) en Мускат (Muscat).
6. **Безалкогольні напої (Bezalkoholni napoi)** - uitspraak: _bezalkoholni napoyi_ - Frisdrank is in Oekraïne ook populair en omvat zowel internationale merken als lokale favorieten. Enkele populaire lokale frisdranken zijn Квас (Kvas), een traditioneel gefermenteerde drank gemaakt van roggebrood, en Збитень (Zbyten), een warme drank gemaakt van honing, kruiden en bessen.


### Gerechten

1. **Борщ (Borsjtsj)** - uitspraak: _borshch_ - Een rode bietensoep, geserveerd met zure room. Het is een kenmerkend gerecht van de Oekraïense keuken en wordt vaak geserveerd met knoflookbrood (пампушки).
2. **Вареники (Varenyky)** - uitspraak: _varenyky_ - Oekraïense dumplings gevuld met verschillende ingrediënten, zoals aardappelen, kool, vlees, bessen of kwark. Ze worden meestal geserveerd met zure room en kunnen zoet of hartig zijn.
3. **Голубці (Holubtsi)** - uitspraak: _holubtsi_ - Koolbladeren gevuld met een mengsel van rijst en gehakt, gekookt in tomatensaus. Het is een populair gerecht in Oekraïne en andere Slavische landen.
4. **Деруни (Deruny)** - uitspraak: _deruny_ - Aardappelpannenkoekjes, geraspte aardappelen gemengd met ei, bloem en uien, gebakken tot ze goudbruin en knapperig zijn. Ze worden vaak geserveerd met zure room of appelmoes.
5. **Сало (Salo)** - uitspraak: _salo_ - Gezouten en gerookt varkensvet, vaak geserveerd als voorgerecht met roggebrood, knoflook en augurken. Het is een traditioneel Oekraïens gerecht en wordt vaak gegeten met горілка (horilka).


## Vervoer en richtingen

Hier geven we je informatie die helpt om je te verplaatsen in Oekraïne en om hulp te vragen bij het navigeren. We voegen ook enkele bestemmingen toe, zo kun je wellicht bij aankomst een lekkere *Борщ* en *Узвар* bestellen. 

### Vervoersmiddelen

| Oekraïens | Uitspraak | Nederlands |
|-----------|-----------|------------|
| автомобіль | avtomobil' | auto |
| автобус | avtobus | bus |
| тролейбус | troleibus | trolleybus |
| трамвай | tramvai | tram |
| метро | metro | metro |
| поїзд | pojizd | trein |
| велосипед | velosyped | fiets |
| таксі | taksi | taxi |

### Richtingen

| Oekraïens | Uitspraak | Nederlands |
|-----------|-----------|------------|
| вперед | vpered | vooruit |
| назад | nazad | achteruit |
| вліво | vlivo | naar links |
| вправо | vpravo | naar rechts |
| прямо | pryamo | rechtdoor |
| повернути | povernuty | afslaan |
| стоп | stop | stop |

### Bestemmingen

Deze tabel bevat enkele van de meest voorkomende bestemmingen waar je mogelijk naartoe wilt gaan tijdens je verblijf in Oekraïne. Gebruik de eerder genoemde richtingen en vervoersmiddelen in combinatie met deze bestemmingen om je weg te vinden en te vragen naar specifieke locaties.

| Oekraïens | Uitspraak | Nederlands |
|-----------|-----------|------------|
| ресторан | restoran | restaurant |
| готель | hotel' | hotel |
| аеропорт | aeroport | vliegveld |
| залізничний вокзал | zaliznychnyi vokzal | treinstation |
| автовокзал | avtovokzal | busstation |
| музей | muzei | museum |
| парк | park | park |
| театр | teatr | theater |
| бібліотека | biblioteka | bibliotheek |
| супермаркет | supermarket | supermarkt |




<!-- ## Kleuren -->

<!-- Basis kleuren zoals rood, blauw, groen, geel, etc. -->
